import PDFDocument from "pdfkit";
import type { DocumentSession } from "../types.js";

const DISCLAIMER =
  "This brief was generated by an AI assistant to help you prepare for a conversation with a " +
  "qualified legal professional. It is not legal advice and may contain errors or omissions. " +
  "Verify all cited clauses against the original document.";

/**
 * Builds a "Prep for My Lawyer" PDF brief: a structured document a user can
 * bring to a consultation to save time - issue summary, flagged clauses,
 * and the questions they've been discussing with the assistant so far.
 */
export function generateBriefPdf(session: DocumentSession): PDFKit.PDFDocument {
  const doc = new PDFDocument({ margin: 50, info: { Title: `Legal Prep Brief - ${session.fileName}` } });

  doc.fontSize(20).text("Legal Prep Brief", { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(10).fillColor("#555").text(`Document: ${session.fileName}`);
  doc.text(`Generated: ${new Date().toLocaleString()}`);
  doc.moveDown();

  doc.fillColor("#B00020").fontSize(10).text(DISCLAIMER, { align: "left" });
  doc.fillColor("black");
  doc.moveDown();

  doc.fontSize(14).text("Summary", { underline: true });
  doc.fontSize(11).text(session.analysis.summary);
  doc.moveDown();

  const highRisk = session.analysis.clauses.filter((c) => c.risk === "high" || c.risk === "medium");
  doc.fontSize(14).text("Flagged Clauses to Discuss", { underline: true });
  doc.moveDown(0.25);

  if (highRisk.length === 0) {
    doc.fontSize(11).text("No high or medium risk clauses were flagged.");
  } else {
    highRisk.forEach((clause) => {
      doc
        .fontSize(11)
        .fillColor("#B00020")
        .text(`Clause ${clause.index} - ${clause.category.replace(/_/g, " ")} (${clause.risk} risk)`, {
          continued: false
        });
      doc.fillColor("black").text(clause.plainLanguage);
      doc.fontSize(9).fillColor("#555").text(`Why flagged: ${clause.rationale}`);
      doc.fontSize(9).fillColor("#888").text(`Original text: "${clause.text.slice(0, 400)}"`);
      doc.fillColor("black");
      doc.moveDown(0.5);
    });
  }

  doc.moveDown();
  doc.fontSize(14).text("Questions Discussed With the Assistant", { underline: true });
  doc.moveDown(0.25);

  const userQuestions = session.chatHistory.filter((m) => m.role === "user");
  if (userQuestions.length === 0) {
    doc.fontSize(11).text("No questions were asked yet. Consider asking about termination, fees, and renewal terms.");
  } else {
    userQuestions.forEach((message, i) => {
      doc.fontSize(11).text(`${i + 1}. ${message.content}`);
    });
  }

  doc.end();
  return doc;
}
